name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Publish Blazor app
      run: dotnet publish BlazorToastWebTest.csproj -c Release -o release

    - name: Update base href
      run: sed -i 's|<base href="/" />|<base href="/BlazorToastWebTest/" />|' release/wwwroot/index.html

    - name: Copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Create .nojekyll to disable Jekyll processing
      run: touch release/wwwroot/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: release/wwwroot
        publish_branch: gh-pages
